import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { GraphQLClient, gql } from "graphql-request";
import BlogCard from '../components/BlogCard.js';

interface Author {
  name: string;
  avatar: {
    url: string;
  };
}

interface CoverPhoto {
  url: string;
}

interface Post {
  author: Author;
  coverPhoto: CoverPhoto;
  id: string;
  title: string;
  datePublished: string;
  slug: string;
}

const graphcms = new GraphQLClient(
  "https://api-eu-west-2.hygraph.com/v2/clbimpglo1rgi01uredh6do8w/master");

const QUERY = gql`
{
  posts {
    author {
      name
      avatar {
        url
      }
    }
    coverPhoto {
      url
    }
    id
    title
    datePublished
    slug
  }
}
`;

export async function getStaticProps(){
  const { posts } = await graphcms.request(QUERY);
  return {
    props: {
      posts,
    },
    revalidate: 10,
  };
}

const Home: React.FC<{ posts: Post[] }> = ({ posts }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {posts.map((post) => (
          <BlogCard
            title={post.title}
            author={post.author}
            coverPhoto={post.coverPhoto}
            key={post.id}
            datePublished={post.datePublished}
            slug={post.slug}
          />
        ))}
      </main>

    </div>
  );
};

export default Home;



